services:
  database:
    image: 'postgres'
    container_name: 'postgres_event_booking'
    environment:
      - 'POSTGRES_PASSWORD=Postgres@007'
      - 'POSTGRES_DB=event_booking_db'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./postgres_event_booking:/var/lib/postgresql/data
#      - ./create-database.sql:/docker-entrypoint-initdb.d/create_database.sql